/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Pokedex: typeof import('./src/components/Pokedex.vue')['default']
    PokemonTable: typeof import('./src/components/PokemonTable.vue')['default']
  }
}
