/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Favorite: typeof import('./src/components/Favorite.vue')['default']
    Pokedex: typeof import('./src/components/Pokedex.vue')['default']
    PokemonImage: typeof import('./src/components/PokemonImage.vue')['default']
    PokemonTable: typeof import('./src/components/PokemonTable.vue')['default']
  }
}
